/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import Parking.SetUp;
import config.dcConnector;
import config.passwordHash;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author TABANG
 */
public class VehicleInformation extends javax.swing.JInternalFrame {

   
    public VehicleInformation() {
        initComponents(); 
        table();
        displayData();
        
          this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        
    }
   
    Connection connect;
    PreparedStatement pst1;
    PreparedStatement pst2;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        j2 = new javax.swing.JLabel();
        j3 = new javax.swing.JLabel();
        j4 = new javax.swing.JLabel();
        j6 = new javax.swing.JLabel();
        V_b = new javax.swing.JTextField();
        V_pn = new javax.swing.JTextField();
        V_at = new javax.swing.JTextField();
        V_vt = new javax.swing.JComboBox<>();
        V_add = new javax.swing.JButton();
        V_Cc = new javax.swing.JTextField();
        j5 = new javax.swing.JLabel();
        j1 = new javax.swing.JLabel();
        V_Cn = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        V_tt = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        j7 = new javax.swing.JLabel();
        Ids = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        VDB = new javax.swing.JTable();

        jPanel1.setBackground(new java.awt.Color(2, 16, 36));

        jPanel2.setBackground(new java.awt.Color(2, 16, 36));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        j2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        j2.setForeground(new java.awt.Color(125, 160, 202));
        j2.setText("Brand");

        j3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        j3.setForeground(new java.awt.Color(125, 160, 202));
        j3.setText("Plate Number");

        j4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        j4.setForeground(new java.awt.Color(125, 160, 202));
        j4.setText("Arival Time");

        j6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        j6.setForeground(new java.awt.Color(125, 160, 202));
        j6.setText("Vehicle Type");

        V_vt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Car", "Motorcycle", "Truck", "Van", "Bus", "Sikad" }));
        V_vt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V_vtActionPerformed(evt);
            }
        });

        V_add.setBackground(new java.awt.Color(2, 16, 36));
        V_add.setText("ADD");
        V_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                V_addActionPerformed(evt);
            }
        });

        j5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        j5.setForeground(new java.awt.Color(125, 160, 202));
        j5.setText("Colour");

        j1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        j1.setForeground(new java.awt.Color(125, 160, 202));
        j1.setText("Company Name");

        jButton1.setBackground(new java.awt.Color(2, 16, 36));
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(2, 16, 36));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(125, 160, 202));
        jLabel2.setText("Ticket No");

        jButton3.setBackground(new java.awt.Color(2, 16, 36));
        jButton3.setText("New");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        j7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        j7.setForeground(new java.awt.Color(125, 160, 202));
        j7.setText("ID");

        Ids.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(j6)
                            .addComponent(j5)
                            .addComponent(j4)
                            .addComponent(j3)
                            .addComponent(j2)
                            .addComponent(j7))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(V_add, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(29, 29, 29))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Ids, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                                    .addComponent(V_b, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(V_vt, javax.swing.GroupLayout.Alignment.LEADING, 0, 153, Short.MAX_VALUE)
                                    .addComponent(V_Cc, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(V_at, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(V_pn, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(V_tt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(V_Cn, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(30, 30, 30))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(j1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ids, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(j7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j1)
                    .addComponent(V_Cn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(V_tt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j2)
                    .addComponent(V_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j3)
                    .addComponent(V_pn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j4)
                    .addComponent(V_at, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j5)
                    .addComponent(V_Cc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(j6)
                    .addComponent(V_vt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(V_add)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(193, 232, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(193, 232, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vehicle Details");

        VDB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        VDB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VDBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(VDB);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void displayData(){
        try{
            dcConnector dbc = new dcConnector();
            ResultSet rs = dbc.getData("SELECT ID, TicketNo, c_name , b_brand , p_plate, a_at ,c_c, v_type FROM  parking");
            VDB.setModel(DbUtils.resultSetToTableModel(rs));
             rs.close();
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());
        
        }
        
    
       }
    
        
    
   public void table() {
      int rowIndex = VDB.getSelectedRow();
    if (rowIndex != -1) { // Check if a row is selected
        try {
            dcConnector dc = new dcConnector();   
            TableModel tbl = VDB.getModel();
            ResultSet Rs = dc.getData("SELECT * FROM parking WHERE ...");

            DefaultTableModel df = (DefaultTableModel) VDB.getModel();
            df.setRowCount(0);

            while (Rs.next()) {
                Vector<String> row = new Vector<>();
                row.add(String.valueOf(Rs.getInt("TicketNo")));
                row.add(Rs.getString("c_name"));
                row.add(Rs.getString("p_plate"));
                row.add(Rs.getString("a_at"));
                row.add(Rs.getString("c_c"));
                row.add(Rs.getString("b_brand"));
                row.add(Rs.getString("v_type"));
                df.addRow(row);
            }
        } catch(SQLException ex) {
            System.out.println("Errors: "+ex.getMessage());
        }
    } else {
        // Handle the case when no row is selected
        System.out.println("No row is selected.");
    }

   }

 
      
    
    
    
    private void V_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V_addActionPerformed
        
        // Get data from GUI fields
        String Tt = V_tt.getText();
        String Cn = V_Cn.getText();
        String Br = V_b.getText();
        String Pn = V_pn.getText();
        String At = V_at.getText();
        String C  = V_Cc.getText();
        String Vt = V_vt.getSelectedItem().toString();

        // Insert data into the database
        if (Tt.isEmpty() || Cn.isEmpty() || Br.isEmpty() || Pn.isEmpty() || At.isEmpty() || C.isEmpty() || Vt.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Please fill in all the details.", "Error", JOptionPane.ERROR_MESSAGE);
} else {
    try {
        Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/userandadmin", "root", "");
        String query = "INSERT INTO parking (TicketNo, c_name, b_brand, p_plate, a_at, c_c, v_type) VALUES (?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement pst = connect.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
        pst.setString(1, Tt);
        pst.setString(2, Cn);
        pst.setString(3, Br);
        pst.setString(4, Pn);
        pst.setString(5, At);
        pst.setString(6, C);
        pst.setString(7, Vt);
        pst.executeUpdate();

        // Get the auto-generated ID
        ResultSet generatedKeys = pst.getGeneratedKeys();
        if (generatedKeys.next()) {
            int id = generatedKeys.getInt(1);
            // Update the table with the new entry
            DefaultTableModel model = (DefaultTableModel) VDB.getModel();
            model.addRow(new Object[]{id, Tt, Cn, Br, Pn, At, C, Vt});
        }
        JOptionPane.showMessageDialog(null, "Details added successfully!");
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error adding details to the database.", "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    }//GEN-LAST:event_V_addActionPerformed

    private void V_vtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_V_vtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_V_vtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String id = Ids.getText();
    String Tt = V_tt.getText();
    String Cn = V_Cn.getText();
    String Br = V_b.getText();
    String Pn = V_pn.getText();
    String At = V_at.getText();
    String C = V_Cc.getText();
    String Vt = V_vt.getSelectedItem().toString();

    // Update data in the database
    if (id.isEmpty() || Tt.isEmpty() || Cn.isEmpty() || Br.isEmpty() || Pn.isEmpty() || At.isEmpty() || C.isEmpty() || Vt.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please fill in all the details.", "Error", JOptionPane.ERROR_MESSAGE);
    } else {
        try {
            Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/userandadmin", "root", "");
            String query = "UPDATE parking SET TicketNo = ?, c_name = ?, b_brand = ?, p_plate = ?, a_at = ?, c_c = ?, v_type = ? WHERE ID = ?";
            PreparedStatement pst = connect.prepareStatement(query);
            pst.setString(1, Tt);
            pst.setString(2, Cn);
            pst.setString(3, Br);
            pst.setString(4, Pn);
            pst.setString(5, At);
            pst.setString(6, C);
            pst.setString(7, Vt);
            pst.setString(8, id);
            pst.executeUpdate();

            // Update the table model
            DefaultTableModel model = (DefaultTableModel) VDB.getModel();
            int selectedRow = VDB.getSelectedRow();
            model.setValueAt(id, selectedRow, 0);
            model.setValueAt(Tt, selectedRow, 1);
            model.setValueAt(Cn, selectedRow, 2);
            model.setValueAt(Br, selectedRow, 3);
            model.setValueAt(Pn, selectedRow, 4);
            model.setValueAt(At, selectedRow, 5);
            model.setValueAt(C, selectedRow, 6);
            model.setValueAt(Vt, selectedRow, 7);

            JOptionPane.showMessageDialog(null, "Details updated successfully!");
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Error updating details in the database.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   int selectedRow = VDB.getSelectedRow();
if (selectedRow != -1) { 
    try {
        // Get the unique identifier from the selected row
        String id = VDB.getValueAt(selectedRow, 0).toString();
        
        // Remove the row from the table model
        DefaultTableModel model = (DefaultTableModel) VDB.getModel();
        model.removeRow(selectedRow);

        // Connect to the database
        Connection connect = DriverManager.getConnection("jdbc:mysql://localhost:3306/userandadmin", "root", "");
        String query = "DELETE FROM parking WHERE id = ?";
        PreparedStatement pst = connect.prepareStatement(query);
        pst.setString(1, id);
        
        // Execute the delete statement
        int rowsAffected = pst.executeUpdate();

        // Check if the deletion was successful
        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "Entry deleted successfully!");
        } else {
            JOptionPane.showMessageDialog(null, "Error: Entry not found in the database.", "Error", JOptionPane.ERROR_MESSAGE);
        }

        // Close the resources
        pst.close();
        connect.close();
    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error deleting entry from the database.", "Error", JOptionPane.ERROR_MESSAGE);
    }
} else {
    JOptionPane.showMessageDialog(null, "Please select a row to delete.", "Error", JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
        Ids.setText("");
    V_tt.setText("");
    V_Cn.setText("");
    V_b.setText("");
    V_pn.setText("");
    V_at.setText("");
    V_Cc.setText("");
    V_vt.setSelectedIndex(0); 
   


    }//GEN-LAST:event_jButton3ActionPerformed

    private void VDBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VDBMouseClicked
        // TODO add your handling code here:
        int selectedRow = VDB.getSelectedRow();
        Ids.setText(VDB.getValueAt(selectedRow, 0).toString());
        V_tt.setText(VDB.getValueAt(selectedRow, 1).toString());
        V_Cn.setText(VDB.getValueAt(selectedRow, 2).toString());
        V_b.setText(VDB.getValueAt(selectedRow, 3).toString());
        V_pn.setText(VDB.getValueAt(selectedRow, 4).toString());
        V_at.setText(VDB.getValueAt(selectedRow, 5).toString());
        V_Cc.setText(VDB.getValueAt(selectedRow, 6).toString());
        V_vt.setSelectedItem(VDB.getValueAt(selectedRow, 7).toString());
   
   
  
    }//GEN-LAST:event_VDBMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField Ids;
    private javax.swing.JTable VDB;
    private javax.swing.JTextField V_Cc;
    private javax.swing.JTextField V_Cn;
    private javax.swing.JButton V_add;
    private javax.swing.JTextField V_at;
    private javax.swing.JTextField V_b;
    private javax.swing.JTextField V_pn;
    private javax.swing.JTextField V_tt;
    private javax.swing.JComboBox<String> V_vt;
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j4;
    private javax.swing.JLabel j5;
    private javax.swing.JLabel j6;
    private javax.swing.JLabel j7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
