/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package admin;

import Parking.SetUp;
import admin.UserForm;
import com.mysql.jdbc.Connection;
import config.dcConnector;
import config.session;
import java.awt.Color;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author PC-
 */
public class UserForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginFrom
     */
    public UserForm() {
        initComponents();
        displayData();
        
    }
    java.sql.Connection connect;
    PreparedStatement pst1;
    PreparedStatement pst2;

    Color navcolor = new Color(7,46,51);
    Color hovercolor = new Color(41,77,97);
    

    
       public void displayData(){
        try{
            dcConnector dbc = new dcConnector();
            ResultSet rs = dbc.getData("SELECT u_id, u_Email , u_Fname , u_Lname, u_Username ,u_type FROM  ttb");
            Tb.setModel(DbUtils.resultSetToTableModel(rs));
             rs.close();
        }catch(SQLException ex){
            System.out.println("Errors: "+ex.getMessage());
        
        }
        
    
       }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        AD_id = new javax.swing.JLabel();
        Add = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Edit = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Delet = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Delet1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        f = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tb = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(7, 46, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/account (1).png"))); // NOI18N

        jLabel8.setBackground(new java.awt.Color(204, 204, 204));
        jLabel8.setFont(new java.awt.Font("Sitka Small", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(109, 165, 192));
        jLabel8.setText("Current  User");

        AD_id.setBackground(new java.awt.Color(204, 204, 204));
        AD_id.setFont(new java.awt.Font("Sitka Small", 1, 10)); // NOI18N
        AD_id.setForeground(new java.awt.Color(109, 165, 192));
        AD_id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AD_id.setText("ID");

        Add.setBackground(new java.awt.Color(7, 46, 51));
        Add.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                AddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                AddMouseExited(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Sitka Small", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(109, 165, 192));
        jLabel6.setText("ADD");

        javax.swing.GroupLayout AddLayout = new javax.swing.GroupLayout(Add);
        Add.setLayout(AddLayout);
        AddLayout.setHorizontalGroup(
            AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AddLayout.setVerticalGroup(
            AddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        Edit.setBackground(new java.awt.Color(7, 46, 51));
        Edit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditMouseExited(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(204, 204, 204));
        jLabel9.setFont(new java.awt.Font("Sitka Small", 1, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(109, 165, 192));
        jLabel9.setText("EDIT");

        javax.swing.GroupLayout EditLayout = new javax.swing.GroupLayout(Edit);
        Edit.setLayout(EditLayout);
        EditLayout.setHorizontalGroup(
            EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EditLayout.setVerticalGroup(
            EditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        Delet.setBackground(new java.awt.Color(7, 46, 51));
        Delet.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Delet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeletMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeletMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeletMouseExited(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Sitka Small", 1, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(109, 165, 192));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("DELETE");

        javax.swing.GroupLayout DeletLayout = new javax.swing.GroupLayout(Delet);
        Delet.setLayout(DeletLayout);
        DeletLayout.setHorizontalGroup(
            DeletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DeletLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DeletLayout.setVerticalGroup(
            DeletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        Delet1.setBackground(new java.awt.Color(7, 46, 51));
        Delet1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Delet1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Delet1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Delet1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Delet1MouseExited(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(204, 204, 204));
        jLabel11.setFont(new java.awt.Font("Sitka Small", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(109, 165, 192));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Print");

        javax.swing.GroupLayout Delet1Layout = new javax.swing.GroupLayout(Delet1);
        Delet1.setLayout(Delet1Layout);
        Delet1Layout.setHorizontalGroup(
            Delet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Delet1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Delet1Layout.setVerticalGroup(
            Delet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AD_id)
                .addGap(53, 53, 53))
            .addComponent(Delet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel8))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addComponent(Delet1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Delet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Delet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AD_id)
                .addGap(36, 36, 36))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 40, 120, 430);

        jPanel3.setBackground(new java.awt.Color(12, 112, 117));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Sitka Subheading", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(109, 165, 192));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("USER FROM");

        f.setBackground(new java.awt.Color(12, 112, 117));
        f.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                fMouseEntered(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic Light", 3, 11)); // NOI18N
        jLabel3.setText("Back");

        javax.swing.GroupLayout fLayout = new javax.swing.GroupLayout(f);
        f.setLayout(fLayout);
        fLayout.setHorizontalGroup(
            fLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        fLayout.setVerticalGroup(
            fLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 453, Short.MAX_VALUE)
                .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 610, 40);

        jPanel4.setBackground(new java.awt.Color(5, 22, 26));

        Tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tb.setSelectionBackground(new java.awt.Color(12, 112, 117));
        jScrollPane1.setViewportView(Tb);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(120, 40, 490, 430);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
           
        session sess = session.getInstance();
        AD_id.setText(""+sess.getId());

    }//GEN-LAST:event_formWindowActivated

    private void AddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseEntered

         Add.setBackground(hovercolor);
    }//GEN-LAST:event_AddMouseEntered

    private void AddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseExited
         Add.setBackground(navcolor);

    }//GEN-LAST:event_AddMouseExited

    
    private void AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddMouseClicked
           MakeUser Mu = new MakeUser();
           Mu.setVisible(true);
           Mu.remove.setEnabled(false);
           Mu.select.setEnabled(true);
           this.dispose();
           
           
                   

    }//GEN-LAST:event_AddMouseClicked

    private void EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMouseClicked
        int rowIndex = Tb.getSelectedRow();
        
        if(rowIndex <0){
                
            JOptionPane.showMessageDialog(null,"Please select an Item");
        }else{
        try{     
             dcConnector dc = new dcConnector();   
             TableModel tbl = Tb.getModel();
             ResultSet rs = dc.getData("SELECT * FROM   ttb WHERE u_id = '"+tbl.getValueAt(rowIndex, 0)+"'");
            
         if(rs.next()){    
             MakeUser Mu = new MakeUser();
             Mu.uid.setText(""+rs.getInt("u_id"));
             Mu.fn.setText(""+rs.getString("u_Fname"));
             Mu.ln.setText(""+rs.getString("u_Lname"));
             Mu.em.setText(""+rs.getString("u_Email"));
             Mu.us.setText(""+rs.getString("u_Username"));
             Mu.pw.setText(""+rs.getString("u_Password"));             
             Mu.ut.setSelectedItem(""+rs.getString("u_type"));
             Mu.ut1.setSelectedItem(""+rs.getString("u_status"));
             Mu.image.setIcon(Mu.ResizeImage(rs.getString("u_image"),null, Mu.image));
             Mu.oldpath = rs.getString("u_image"); 
             Mu.path = rs.getString("u_image");
             Mu.destination = rs.getString("u_image");
             Mu.add1.setEnabled(false);
             Mu.Update.setEnabled(true);
             Mu.setVisible(true);
            
          if(rs.getString("u_image").isEmpty()){
              Mu.select.setEnabled(true);
              Mu.remove.setEnabled(false);
          }else{
              Mu.select.setEnabled(false);
              Mu.remove.setEnabled(true);
          }   
             
             this.dispose();
         }
         
        }catch(SQLException ex){
            
            System.out.println(""+ex);
        }
       
    }//GEN-LAST:event_EditMouseClicked
    }
    
    private void EditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMouseEntered
           Edit.setBackground(hovercolor);
    }//GEN-LAST:event_EditMouseEntered

    private void EditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMouseExited
           Edit.setBackground(navcolor);
    }//GEN-LAST:event_EditMouseExited

    private void DeletMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletMouseClicked

      
     /*
        
           DefaultTableModel tbl = (DefaultTableModel) Tb.getModel();
             
            if(Tb.getSelectedRowCount() == 1){
                tbl.removeRow(Tb.getSelectedRow());  
            }else{
                if(Tb.getRowCount() == 0){
                    JOptionPane.showMessageDialog(null, "Table is Empty");
                }else{
                    JOptionPane.showMessageDialog(null, "Please Selet Single Row For Delete");
          }      
            }*/
                
           
    /* try {
         int rowIndex = Tb.getSelectedRow();
        if (rowIndex >= 0){ 
            Class.forName("com.mysql.jdbc.Driver");
            connect  = DriverManager.getConnection("jdbc:mysql://localhost:3306/userandadmin", "root", "");
            
            String value = (Tb.getModel().getValueAt(rowIndex, 0).toString());
            String query = "DELETE FROM ttb WHERE u_id = " + value;
            PreparedStatement pst = connect.prepareStatement(query);
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel)Tb.getModel();
            model.setRowCount(0);
            displayData();
            JOptionPane.showMessageDialog(null, "Deleted Successfully");
            }else{
                JOptionPane.showMessageDialog(null, "Please Select First to Delet");
            }
          } catch (ClassNotFoundException ex) {
            Logger.getLogger(SetUp.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(UserForm.class.getName()).log(Level.SEVERE, null, ex);
        }  */
    }//GEN-LAST:event_DeletMouseClicked

    private void DeletMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletMouseEntered
            Delet.setBackground(hovercolor);
    }//GEN-LAST:event_DeletMouseEntered

    private void DeletMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeletMouseExited
             Delet.setBackground(navcolor);
    }//GEN-LAST:event_DeletMouseExited

    private void fMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fMouseClicked
        AdminDash ad = new AdminDash();
           ad.setVisible(true);
           this.dispose();
            
    }//GEN-LAST:event_fMouseClicked

    private void fMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fMouseEntered
        
    }//GEN-LAST:event_fMouseEntered

    private void Delet1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delet1MouseClicked
        int rowIndex = Tb.getSelectedRow();
        
        if(rowIndex <0){
                
            JOptionPane.showMessageDialog(null,"Please select an Item");
        }else{
        try{     
             dcConnector dc = new dcConnector();   
             TableModel tbl = Tb.getModel();
             ResultSet rs = dc.getData("SELECT * FROM   ttb WHERE u_id = '"+tbl.getValueAt(rowIndex, 0)+"'");
            
         if(rs.next()){    
             IndividualPrinting ipt = new IndividualPrinting();
             ipt.uid.setText(""+rs.getInt("u_id"));
             ipt.fn.setText(""+rs.getString("u_Fname"));
             ipt.ln.setText(""+rs.getString("u_Lname"));
             ipt.em.setText(""+rs.getString("u_Email"));
             ipt.us.setText(""+rs.getString("u_Username"));
             ipt.at.setText(""+rs.getString("u_type"));
             ipt.st.setText(""+rs.getString("u_status"));
             ipt.image.setIcon(ipt.ResizeImage(rs.getString("u_image"),null, ipt.image));
             ipt.setVisible(true);
             this.dispose();
         }
         
        }catch(SQLException ex){
            
            System.out.println(""+ex);
        }
       
    }     
    }//GEN-LAST:event_Delet1MouseClicked

    private void Delet1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delet1MouseEntered
            Delet1.setBackground(hovercolor);
    }//GEN-LAST:event_Delet1MouseEntered

    private void Delet1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Delet1MouseExited
            Delet1.setBackground(navcolor);
    }//GEN-LAST:event_Delet1MouseExited

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AD_id;
    private javax.swing.JPanel Add;
    private javax.swing.JPanel Delet;
    private javax.swing.JPanel Delet1;
    private javax.swing.JPanel Edit;
    private javax.swing.JTable Tb;
    private javax.swing.JPanel f;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
